name: 🐞 Bug Report
description: Report a defect in the WSO2 Integration Platform
title: "[Bug]: "
labels: ["Type/Bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the details below.

  - type: input
    id: version
    attributes:
      label: Product Version
      description: Which version are you using?
      placeholder: e.g., 1.2.3
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: Clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / Screenshots