name: 📋 Engineering Task
description: Internal engineering execution task
title: "[Task]: "
labels: ["Type/Task"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for engineering execution tasks such as:
        - Research work and proposals
        - Implementation work
        - Test case additions / coverage increase
        - Refactoring
        - Documentation updates
        - CI/CD updates
        - Dependency upgrades

  - type: dropdown
    id: task_category
    attributes:
      label: Task Category
      description: Select the category that best describes this task.
      options:
        - Research / Proposal
        - Implementation
        - Test Coverage
        - Refactoring
        - Documentation
        - CI/CD Update
        - Dependency Upgrade
    validations:
      required: true

  - type: input
    id: parent_issue
    attributes:
      label: Parent Issue (Feature / Improvement / Bug)
      description: Provide the parent issue number or URL. If not applicable, enter "N/A".
      placeholder: e.g., #1234 or https://github.com/org/repo/issues/1234 or N/A
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide background information and reasoning for this task.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope of Work
      description: Clearly define what is included and excluded.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define how we know this task is complete.
      placeholder: |
        - [ ] Implementation complete
        - [ ] Tests added
        - [ ] Documentation updated
        - [ ] CI passing
    validations:
      required: true